[2025-09-19T12:24:14.992+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_generator.generate_and_upload_crypto_data manual__2025-09-19T12:24:12.087085+00:00 [queued]>
[2025-09-19T12:24:15.007+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_generator.generate_and_upload_crypto_data manual__2025-09-19T12:24:12.087085+00:00 [queued]>
[2025-09-19T12:24:15.008+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-09-19T12:24:15.040+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_and_upload_crypto_data> on 2025-09-19 12:24:12.087085+00:00
[2025-09-19T12:24:15.051+0000] {standard_task_runner.py:60} INFO - Started process 976 to run task
[2025-09-19T12:24:15.057+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_generator', 'generate_and_upload_crypto_data', 'manual__2025-09-19T12:24:12.087085+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/crypto_data_generator_dag.py', '--cfg-path', '/tmp/tmp2cjdduv6']
[2025-09-19T12:24:15.059+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask generate_and_upload_crypto_data
[2025-09-19T12:24:15.143+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_data_generator.generate_and_upload_crypto_data manual__2025-09-19T12:24:12.087085+00:00 [running]> on host ece681799ab2
[2025-09-19T12:24:15.298+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_upload_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T12:24:12.087085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T12:24:12.087085+00:00'
[2025-09-19T12:24:15.302+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-19T12:24:15.304+0000] {logging_mixin.py:188} INFO - Generated /tmp/crypto_data_20250919_12.csv
[2025-09-19T12:24:15.328+0000] {logging_mixin.py:188} INFO - Uploaded /tmp/crypto_data_20250919_12.csv to crypto-data/raw-data/2025/09/19/12/crypto_data_20250919_12.csv
[2025-09-19T12:24:15.329+0000] {python.py:201} INFO - Done. Returned value was: {'file_path': 'raw-data/2025/09/19/12/crypto_data_20250919_12.csv', 'records': 'generated'}
[2025-09-19T12:24:15.363+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_data_generator, task_id=generate_and_upload_crypto_data, execution_date=20250919T122412, start_date=20250919T122414, end_date=20250919T122415
[2025-09-19T12:24:15.431+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T12:24:15.457+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
