[2025-09-19T15:15:09.847+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_main.handle_validation_failure scheduled__2025-09-19T15:00:00+00:00 [queued]>
[2025-09-19T15:15:09.862+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_main.handle_validation_failure scheduled__2025-09-19T15:00:00+00:00 [queued]>
[2025-09-19T15:15:09.863+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-19T15:15:09.886+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): handle_validation_failure> on 2025-09-19 15:00:00+00:00
[2025-09-19T15:15:09.893+0000] {standard_task_runner.py:60} INFO - Started process 1772 to run task
[2025-09-19T15:15:09.899+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_main', 'handle_validation_failure', 'scheduled__2025-09-19T15:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpkpf1aaep']
[2025-09-19T15:15:09.904+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask handle_validation_failure
[2025-09-19T15:15:09.982+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_etl_main.handle_validation_failure scheduled__2025-09-19T15:00:00+00:00 [running]> on host ed735ff6f76b
[2025-09-19T15:15:10.116+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='crypto_etl_main' AIRFLOW_CTX_TASK_ID='handle_validation_failure' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-19T15:00:00+00:00'
[2025-09-19T15:15:10.163+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-09-19T15:15:10.164+0000] {logging_mixin.py:188} INFO - 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:00:00+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:15:10.165+0000] {python.py:201} INFO - Done. Returned value was: 
    ❌ ETL Pipeline Failed:
    
    Structure validation failures: 0
    Quality check failures: 0
    Transform/Load failures: 0
    
    Execution Date: 2025-09-19 15:00:00+00:00
    DAG: crypto_etl_main
    
    Please check logs for detailed error information.
    
[2025-09-19T15:15:10.197+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=crypto_etl_main, task_id=handle_validation_failure, execution_date=20250919T150000, start_date=20250919T151509, end_date=20250919T151510
[2025-09-19T15:15:10.232+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-19T15:15:10.269+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
